### ISSUE TITLE
Doesn't support latest Swift

### ISSUE THREAD

**Issue by sidan5** [zhuhaow/Specht#6]
Is there any plan to support latest Swift version?

I'm using Xcode 8.3 and it has some error syntax related.

**Comment by zhuhaow** [comment]
No, I'm not interested in updating it to keep people who know little about network under the illusion that they can create an app working right with NEKit and TUN by copying and pasting a few codes they don't understand. You can say this repo is already deprecated as people should not need it at all. It's not very likely I will ever update this project.

A few things have changed in NEKit which have not been updated in Specht. But since you want to work with it, I think you can sort them out.（・∀・）

**Comment by sidan5** [comment]
@zhuhaow So do you say there in no need anymore to use NEKit and everything could be done with Network Extension?

Sorry but I'm new to NE and want to know where to start. Would really appreciate your professional suggestion.

Thanks!

**Comment by zhuhaow** [comment]
No, I mean things should be very straight forward (for anyone who want to use it) that a demo up-to-date is not a must.

Specht itself is very clear, I do wonder why you need a project with the latest syntax to learn how to work with NE. You are not (and can't be) learning Swift 3 from this project anyway.

**Comment by sidan5** [comment]
I just want something to first compile and run before I playing with it :/

I'll use some old Xcode...
